name: run automated tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test_and_build:
    name: Test and build samples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn -B clean test | tee test.log

      - name: Build package
        run: mvn -B clean package

      - name: Prepare artifacts
        run: mkdir artifacts && cp test.log target/*.jar artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: artifacts
